variables:
  HOST: "peyotedesign.ch.arvandus.ch-meta.net"
  USERNAME: "peyotler"
  PASSWORD: "M3x1co86"

deploy:
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rnev dist/ ./httpdocs/test/ --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
    - master