deploy: // You can name your task however you like
    stage: deploy
    only:
        - master
        deploy:
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u 'elpeyotler','Metall1cA' 'peyotedesign.ch.arvandus.ch-meta.net'; mirror -Rev dist/ ./public_html/test/  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"